platform :ios, '9.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'Example' do
  pod 'xsdk_core', :path => './xsdk_core'
  pod 'xsdk_webchat', :path => './xsdk_webchat'
  pod 'xsdk_apple_push', :path => './xsdk_apple_push'
end
